version: '2'
services:
  jhipstersujanapplicationoauth2-app:
    image: jhipstersujanapplicationoauth2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhipstersujanapplicationoauth2-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jhipsterSujanApplicationOAuth2
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipstersujanapplicationoauth2-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipstersujanapplicationoauth2-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8090:8090
  jhipstersujanapplicationoauth2-mongodb:
    extends:
      file: mongodb.yml
      service: jhipstersujanapplicationoauth2-mongodb
  jhipstersujanapplicationoauth2-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipstersujanapplicationoauth2-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
